name: Build
on: 
  pull_request:
    branches: [ $default-branch ]
defaults: 
  run:
    shell: bash
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python3 --version
        echo "installing pip"
        python3 -m pip install --user --upgrade pip requests  
    - name: Build LaTeX
      run: |
        echo "github repo is ${{ github.repository }}"
        echo "${{github['event']['number']}}"
        my_var="${{ secrets.GITHUB_TOKEN }}"
        if [ -z my_var ]; then echo "\$my_var is NULL"; fi
        dir_to_compile=( $(python .github/workflows/get_directory_to_compile.py ${{ github.repository }} ${{github['event']['number']}} ${{ secrets.GITHUB_TOKEN }} ) )
        echo "dir to compile value $dir_to_compile"
        for dir in $dir_to_compile; do
          cd $PWD/$dir
          enonce="Compile_${dir}_ENONCE"
          solution="Compile_${dir}_ENONCE_SOLUTION"
          latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=. $enonce;
          latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=. $solution;
          cd ..
        done
